### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by gundersona** [frkasper/MacroUtils#12]
The following error message appears when trying to build the jar file using Netbeans 8.1:

A:\StarMacros\nbproject\build-impl.xml:916: The following error occurred while executing this line:
A:\StarMacros\nbproject\build-impl.xml:266: Error running C:\JAVA\jdk1.7.0_51\bin\javac.exe compiler
BUILD FAILED (total time: 6 seconds)

This build is successful using Netbeans 8.0.2. Is there a reason for this? If Netbeans 8.0.2 is necessary for proper building, then the FAQ portion of the wiki should be updated accordingly. Thanks.

**Comment by frkasper** [comment]
Hi there,

Thank you for your interest in MacroUtils.

Interesting message. Sadly I am very short on computing resources today but I was able to do a quick test in NetBeans 8.2 in Linux and build was successful. What I have done in a brand new machine was:

- NetBeans 8.2 was installed beforehand;
- Cloned MacroUtils from GitHub and kept to master branch;
- Added STAR-CCM+ v11.06 JAR files as Ant Libraries;
- Added a Java Platform to point to a valid JDK7 installation;
- Changed the Compiler to JDK7.
- Hit Shift-F11 in NetBeans.

The output is given below:

`ant -f /home/user/mymacros/macroutils -Dnb.internal.action.name=rebuild clean jar
init:
deps-clean:
Created dir: /home/user/mymacros/macroutils/build
Updating property file: /home/user/mymacros/macroutils/build/built-clean.properties
Deleting directory /home/user/mymacros/macroutils/build
clean:
init:
deps-jar:
Created dir: /home/user/mymacros/macroutils/build
Updating property file: /home/user/mymacros/macroutils/build/built-jar.properties
Created dir: /home/user/mymacros/macroutils/build/classes
Created dir: /home/user/mymacros/macroutils/build/empty
Created dir: /home/user/mymacros/macroutils/build/generated-sources/ap-source-output
Compiling 67 source files to /home/user/mymacros/macroutils/build/classes
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
compile:
Created dir: /home/user/mymacros/macroutils/dist
Copying 1 file to /home/user/mymacros/macroutils/build
Copy libraries to /home/user/mymacros/macroutils/dist/lib.
Building jar: /home/user/mymacros/macroutils/dist/MacroUtils.jar
To run this application from the command line without Ant, try:
/home/files/lin64/11.06.011_01/jdk/linux-x86_64/jdk1.7.0_75/bin/java -jar "/home/user/mymacros/macroutils/dist/MacroUtils.jar"
jar:
BUILD SUCCESSFUL (total time: 8 seconds)
`

Sorry if I was unable to reproduce your failure. Sadly I cannot test in other NB versions for the time being.

Thanks again!
Fabio

**Comment by gundersona** [comment]
Thanks for your prompt reply Fabio.

When I tried installing Netbeans 8.2, the installer stated that 8.2 only works with JDK8, and installation only works if you point to JDK8. Maybe you were able to install pointing to JDK8 and then reconfigured it to point to a JDK7 installation? 

Either way Netbeans 8.0.2 worked for me and I am now able to use your library, so this issue can be considered closed. Thanks!

**Comment by frkasper** [comment]
Good point.  In my Linux environment I recall that I need to call NetBeans with some _--jdkhome_ syntax. And I had a JDK8 somewhere. 

Anyway, at some point STAR-CCM+ may migrate to JDK8. When this happen at least you'll have a valid JDK8 installation shipped with it.

Thank you for opening the very first issue of MacroUtils. ;-)
