### ISSUE TITLE
Create streamline scene

### ISSUE THREAD

**Issue by gundersona** [frkasper/MacroUtils#14]
The "streamline" method found in CreateScene.java doesn't successfully create the transparent geometry part displayer (the streamline displayer is created successfully). It appears that the method at fault is "_createDisplayer_Part", specifically the line "pd.addParts(ano);" seems to only work on part surfaces, not parts or regions themselves.

**Comment by frkasper** [comment]
Hi @gundersona,

Thanks for spotting this one. Indeed something got broken. E.g.: if I get the sim file saved in Demo1 and apply the following macro:

`import macroutils.*;
import star.common.*;

public class CreateStreamlineScene extends StarMacro {

    public void execute() {

        MacroUtils mu = new MacroUtils(getActiveSimulation());

        UserDeclarations ud = mu.userDeclarations;

        ud.namedObjects.addAll(mu.get.regions.all(true));

        mu.add.scene.streamline(ud.namedObjects, true).open();

    }

}
`

The outcome is something I was not expecting. I will have a look and hopefully push a fix soon.

Cheers!

**Comment by frkasper** [comment]
It should be fixed now. Please see 4b08be9fa8b6c7b5f6857e406c3f3aedb30f201d.

![demo1_cylinder_streamline](https://cloud.githubusercontent.com/assets/14906384/24017659/3e945348-0a67-11e7-9677-285e552b4d84.png)

Thank you for your interest in MacroUtils.

Regards!
Fabio
