### ISSUE TITLE
STAR CCM+ Zero Gap simulation 

### ISSUE THREAD

**Issue by direwolf0** [frkasper/MacroUtils#34]
Dear Fabio Kasper,

i am working on my thesis right now and working on a simulation of a dynamic valve. I found your video on youtube: 
https://www.youtube.com/watch?v=RYKolUSipLQ&pbjreload=101 which is dealing with the zerogap mechanism. I would 
like to ask if it is possible to: 
1. Maybe get the .sim file of this model? It would be a big help for me in my work!
2. If its not possible, I would like to know if there is a way to contact you for short exchange about Zero Gap simulation stuff?

I would be very happy to hear from you!
Best regards, Eugen

**Comment by frkasper** [comment]
Hi Eugen,

That Youtube video was a toy model made a long time ago and sadly I no longer have those files, nor remember how did I set that up. But it shouldn't be too difficult to reproduce it in a 2D fashion. 

I suggest you trying the customer support portal and go through the tutorials shipped with STAR-CCM+. The key is to respect meshing and time-step requirements, whatever they may be for your particular application.

Good luck!
